import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DashboardHeader } from "../components/DashboardHeader";
import { DashboardTabs } from "../components/DashboardTabs";
import { ErrorBanner } from "../components/ErrorBanner";
import { MswProvider, ReduxProvider } from "../store/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bite Track",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <MswProvider>
            <div className="min-h-screen bg-zinc-50">
              <header className="border-b border-slate-200 bg-white">
                <div className="px-6 py-6">
                  <div className="mx-auto max-w-6xl">
                    <DashboardHeader />
                  </div>
                </div>
                <div className="px-6 pb-4">
                  <div className="mx-auto max-w-6xl">
                    <DashboardTabs />
                  </div>
                </div>
              </header>
              {children}
            </div>
            <ErrorBanner />
          </MswProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
